name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:latest
      working-directory: back-end

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:latest
      working-directory: back-end