name: Deploy Database to Docker Hub

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List directory structure
      run: ls -R back-end

    - name: Build and Push Docker Image as latest
      working-directory: back-end/docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-db:latest -f Dockerfile.db .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-db:latest
