name: Deploy Database to Docker Hub

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: List directory structure
      run: ls -R back-end

    - name: Generate dump.sql
      run: |
        chmod +x ./back-end/docker/dump.sh
        ./back-end/docker/dump.sh
      working-directory: back-end/docker
      env:
        DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

    - name: Build and Push Docker Image as latest
      working-directory: back-end/docker
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-db:latest -f Dockerfile.db .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-db:latest
