name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package
      working-directory: back-end

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get the version for branch push
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
      id: get_version_branch
      run: |
        VERSION=$(git describe --tags --abbrev=0 || echo "no-tags")
        if [ "$VERSION" = "no-tags" ]; then
          echo "No tags found, defaulting to 'latest'"
          VERSION="latest"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Get the version for tag push
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      id: get_version_tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:${{ env.VERSION }}
      working-directory: back-end

    - name: Tag the Docker image as latest
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:latest
      working-directory: back-end

    - name: Push the Docker image with version tag
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:${{ env.VERSION }}
      working-directory: back-end

    - name: Push the Docker image with latest tag
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-analytics-api:latest
      working-directory: back-end
